# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGithub < Formula
  desc ""
  homepage "https://github.com/linuxuserin/go-github"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_Darwin_arm64.tar.gz"
      sha256 "520c0873fa3faaea26f16106b4cd6aa1c20178b0ee238905821ec60250535f2b"

      def install
        bin.install "go-github"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "01e55418eefae89ff713268f9b31dee2e0916947cdec7fa62e99d2bc1eaebd3b"

      def install
        bin.install "go-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_Linux_arm64.tar.gz"
      sha256 "dec867060a893826dc3a398aee0d02b1156f11c44ce123d7882be76e3cc47a18"

      def install
        bin.install "go-github"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_Linux_x86_64.tar.gz"
      sha256 "ecb49901a907fff1942304741a08fb65df2bafc3a0f492a823c3a180b1678502"

      def install
        bin.install "go-github"
      end
    end
  end
end
