# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGithub < Formula
  desc "CLI to fetch github user info"
  homepage "https://github.com/linuxuserin/go-github"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_darwin_amd64.tar.gz"
      sha256 "324dabdb2968e2487a018e6ac6e755b03e730be6e2c6bbb05b428c44efcccead"

      def install
        bin.install "go-github"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_darwin_arm64.tar.gz"
      sha256 "e9d6ace7ba846f0632e9a855ebf7040cbc689073ecb967cda7c72190e8960398"

      def install
        bin.install "go-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_linux_amd64.tar.gz"
      sha256 "9d2dae013fcf0d34eff88afc6f8720b43324fc62d277a77872a1b359953e04c9"

      def install
        bin.install "go-github"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_linux_arm64.tar.gz"
      sha256 "70c3e60da45176a2689f3a4baac1ec64dfde6559a5281e43ec3b14036dfcedc7"

      def install
        bin.install "go-github"
      end
    end
  end
end
