# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGithub < Formula
  desc "CLI to fetch github user info"
  homepage "https://github.com/linuxuserin/go-github"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_darwin_amd64.tar.gz"
      sha256 "3076d45f683fc342d2ec881efc0e4a418c92025d1c81b18a82bf59c63bbff15f"

      def install
        bin.install "go-github"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_darwin_arm64.tar.gz"
      sha256 "8d51054ba57462834a31779169a75181853c7ae762cd27101189e5cb81c3582e"

      def install
        bin.install "go-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_linux_amd64.tar.gz"
      sha256 "cbcbc9c42ff1bf5b7e276b9d52654293f445bef28ea7c277c402814e40f7db8f"

      def install
        bin.install "go-github"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linuxuserin/go-github/releases/download/v0.1.0/go-github_0.1.0_linux_arm64.tar.gz"
      sha256 "46437726fa1593a34dc9fb6adc07975c93377c6eaa16f79f84fc7a4e7ee56468"

      def install
        bin.install "go-github"
      end
    end
  end
end
